export const headersData_xm_stn = [
    {
      name: "Id",
      field: "id",
      sortable: true,
      required: false,
      location: "center",
      showInForm: false,
      showInTable: true,
      clase: "input",
      type: "number",
    },
    {
      name: "Eliminar",
      field: "Eliminar",
      sortable: false,
      required: false,
      location: "center",
      showInForm: false,
      showInTable: true,
      type: "button",
    },
    {
      name: "Creador",
      field: "creador",
      sortable: true,
      required: true,
      location: "center",
      showInForm: false,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "empresa id",
      field: "empresa_id",
      sortable: true,
      required: true,
      location: "center",
      showInForm: false,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "anho",
      field: "anho",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "mes",
      field: "mes",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "Periodo",
      field: "periodo",
      sortable: true,
      required: true,
      location: "center",
      showInForm: false,
      showInTable: true,
      clase: "input",
      type: "text",
      validations: "",
      description: "",
    },
    {
      name: "t_cop_kwh",
      field: "t_cop_kwh",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "t_prima_cop_kwh",
      field: "t_prima_cop_kwh",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "Energia_sin_kwh",
      field: "Energia_sin_kwh",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "Ing_Reg_Bruto_T_cop",
      field: "Ing_Reg_Bruto_T_cop",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "Ing_Compensar_T_cop",
      field: "Ing_Compensar_T_cop",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "Ing_Reg_Neto_T_cop",
      field: "Ing_Reg_Neto_T_cop",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "delta_t_cop_kwh",
      field: "delta_t_cop_kwh",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
  ];

  export const headersData_xm_str = [
    {
      name: "Id",
      field: "id",
      sortable: true,
      required: false,
      location: "center",
      showInForm: false,
      showInTable: true,
      clase: "input",
      type: "number",
    },
    {
      name: "Eliminar",
      field: "Eliminar",
      sortable: false,
      required: false,
      location: "center",
      showInForm: false,
      showInTable: true,
      type: "button",
    },
    {
      name: "Creador",
      field: "creador",
      sortable: true,
      required: true,
      location: "center",
      showInForm: false,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "empresa id",
      field: "empresa_id",
      sortable: true,
      required: true,
      location: "center",
      showInForm: false,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "anho",
      field: "anho",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "mes",
      field: "mes",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "Periodo",
      field: "periodo",
      sortable: true,
      required: true,
      location: "center",
      showInForm: false,
      showInTable: true,
      clase: "input",
      type: "text",
      validations: "",
      description: "",
    },
    {
      name: "total_ingreso_mensual_bruto_str_cop_norte",
      field: "total_ingreso_mensual_bruto_str_cop_norte",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "text",
      validations: "",
      description: "",
    },
    {
      name: "energia_del_str_kwh_norte",
      field: "energia_del_str_kwh_norte",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "cargo_nt_antes_de_compensacion_cd4_cop_kwh_norte",
      field: "cargo_nt_antes_de_compensacion_cd4_cop_kwh_norte",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "cargo_nt_despues_de_compensacion_cd4_cop_kwh_norte",
      field: "cargo_nt_despues_de_compensacion_cd4_cop_kwh_norte",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "cargo_por_uso_dt4_cop_kwh_norte",
      field: "cargo_por_uso_dt4_cop_kwh_norte",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "factor_para_referir_las_medidas_de_energia_del_nt_4_norte",
      field: "factor_para_referir_las_medidas_de_energia_del_nt_4_norte",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "valor_diferencial_despues_de_compensacion_cop_kwh_norte",
      field: "valor_diferencial_despues_de_compensacion_cop_kwh_norte",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "total_ingreso_mensual_bruto_str_cop_sur",
      field: "total_ingreso_mensual_bruto_str_cop_sur",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "energia_del_str_kwh_sur",
      field: "energia_del_str_kwh_sur",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "cargo_nt_antes_de_compensacion_cd4_cop_kwh_sur",
      field: "cargo_nt_antes_de_compensacion_cd4_cop_kwh_sur",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "cargo_nt_despues_de_compensacion_cd4_cop_kwh_sur",
      field: "cargo_nt_despues_de_compensacion_cd4_cop_kwh_sur",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "cargo_por_uso_dt4_cop_kwh_sur",
      field: "cargo_por_uso_dt4_cop_kwh_sur",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "factor_para_referir_las_medidas_de_energia_del_nt_4_sur",
      field: "factor_para_referir_las_medidas_de_energia_del_nt_4_sur",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "valor_diferencial_despues_de_compensacion_cop_kwh_sur",
      field: "valor_diferencial_despues_de_compensacion_cop_kwh_sur",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
  ];