export const headersData_xm_stn = [
  {
    name: "Id",
    field: "id",
    sortable: true,
    required: false,
    location: "center",
    showInForm: false,
    showInTable: true,
    clase: "input",
    type: "number",
  },
  {
    name: "Eliminar",
    field: "Eliminar",
    sortable: false,
    required: false,
    location: "center",
    showInForm: false,
    showInTable: true,
    type: "button",
  },
  {
    name: "Creador",
    field: "creador",
    sortable: true,
    required: true,
    location: "center",
    showInForm: false,
    showInTable: false,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "empresa id",
    field: "empresa_id",
    sortable: true,
    required: true,
    location: "center",
    showInForm: false,
    showInTable: false,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "anho",
    field: "anho",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: false,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "mes",
    field: "mes",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: false,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "Periodo",
    field: "periodo",
    sortable: true,
    required: true,
    location: "center",
    showInForm: false,
    showInTable: true,
    clase: "input",
    type: "text",
    validations: "",
    description: "",
  },
  {
    name: "t_cop_kwh",
    field: "t_cop_kwh",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "t_prima_cop_kwh",
    field: "t_prima_cop_kwh",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "Energia_sin_kwh",
    field: "Energia_sin_kwh",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "Ing_Reg_Bruto_T_cop",
    field: "Ing_Reg_Bruto_T_cop",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "Ing_Compensar_T_cop",
    field: "Ing_Compensar_T_cop",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "Ing_Reg_Neto_T_cop",
    field: "Ing_Reg_Neto_T_cop",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "delta_t_cop_kwh",
    field: "delta_t_cop_kwh",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
];

export const headersData_xm_str = [
  {
    name: "Id",
    field: "id",
    sortable: true,
    required: false,
    location: "center",
    showInForm: false,
    showInTable: true,
    clase: "input",
    type: "number",
  },
  {
    name: "Eliminar",
    field: "Eliminar",
    sortable: false,
    required: false,
    location: "center",
    showInForm: false,
    showInTable: true,
    type: "button",
  },
  {
    name: "Creador",
    field: "creador",
    sortable: true,
    required: true,
    location: "center",
    showInForm: false,
    showInTable: false,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "empresa id",
    field: "empresa_id",
    sortable: true,
    required: true,
    location: "center",
    showInForm: false,
    showInTable: false,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "anho",
    field: "anho",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: false,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "mes",
    field: "mes",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: false,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "Periodo",
    field: "periodo",
    sortable: true,
    required: true,
    location: "center",
    showInForm: false,
    showInTable: true,
    clase: "input",
    type: "text",
    validations: "",
    description: "",
  },
  {
    name: "total_ingreso_mensual_bruto_str_cop_norte",
    field: "total_ingreso_mensual_bruto_str_cop_norte",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "text",
    validations: "",
    description: "",
  },
  {
    name: "energia_del_str_kwh_norte",
    field: "energia_del_str_kwh_norte",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "cargo_nt_antes_de_compensacion_cd4_cop_kwh_norte",
    field: "cargo_nt_antes_de_compensacion_cd4_cop_kwh_norte",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "cargo_nt_despues_de_compensacion_cd4_cop_kwh_norte",
    field: "cargo_nt_despues_de_compensacion_cd4_cop_kwh_norte",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "cargo_por_uso_dt4_cop_kwh_norte",
    field: "cargo_por_uso_dt4_cop_kwh_norte",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "factor_para_referir_las_medidas_de_energia_del_nt_4_norte",
    field: "factor_para_referir_las_medidas_de_energia_del_nt_4_norte",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "valor_diferencial_despues_de_compensacion_cop_kwh_norte",
    field: "valor_diferencial_despues_de_compensacion_cop_kwh_norte",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "total_ingreso_mensual_bruto_str_cop_sur",
    field: "total_ingreso_mensual_bruto_str_cop_sur",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "energia_del_str_kwh_sur",
    field: "energia_del_str_kwh_sur",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "cargo_nt_antes_de_compensacion_cd4_cop_kwh_sur",
    field: "cargo_nt_antes_de_compensacion_cd4_cop_kwh_sur",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "cargo_nt_despues_de_compensacion_cd4_cop_kwh_sur",
    field: "cargo_nt_despues_de_compensacion_cd4_cop_kwh_sur",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "cargo_por_uso_dt4_cop_kwh_sur",
    field: "cargo_por_uso_dt4_cop_kwh_sur",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "factor_para_referir_las_medidas_de_energia_del_nt_4_sur",
    field: "factor_para_referir_las_medidas_de_energia_del_nt_4_sur",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
  {
    name: "valor_diferencial_despues_de_compensacion_cop_kwh_sur",
    field: "valor_diferencial_despues_de_compensacion_cop_kwh_sur",
    sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: "",
  },
];

export const headersData_xm_d015 = [  { name: "id", field: "id",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "creador", field: "creador",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "empresa_id", field: "empresa_id",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "anho", field: "anho",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "mes", field: "mes",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_por_uso_dt1_cop_kwh", field: "cargo_por_uso_dt1_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_por_uso_dt2_cop_kwh", field: "cargo_por_uso_dt2_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_por_uso_dt3_cop_kwh", field: "cargo_por_uso_dt3_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_de_inversion_cdi1_cop_kwh", field: "cargo_de_inversion_cdi1_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_por_aom_cda1_cop_kwh", field: "cargo_por_aom_cda1_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_nivel_de_tension_cd2_cop_kwh", field: "cargo_nivel_de_tension_cd2_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_nivel_de_tension_cd3_cop_kwh", field: "cargo_nivel_de_tension_cd3_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_nivel_de_tension_cd3_2_cop_kwh", field: "cargo_nivel_de_tension_cd3_2_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_nivel_de_tension_cd4_cop_kwh", field: "cargo_nivel_de_tension_cd4_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cargo_por_incentivos_dtcs_cop_kwh", field: "cargo_por_incentivos_dtcs_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "fraccion_dtcs_cop_kwh", field: "fraccion_dtcs_cop_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
// Continuación del arreglo
{ name: "ia1", field: "ia1",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "ia2", field: "ia2",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "ia3", field: "ia3",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iaa1_cop", field: "iaa1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iaa2_cop", field: "iaa2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iaa3_cop", field: "iaa3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "irm1_cop", field: "irm1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "irm2_cop", field: "irm2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "irm3_cop", field: "irm3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "fm", field: "fm",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iaaom1_cop", field: "iaaom1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iaaom2_cop", field: "iaaom2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iaaom3_cop", field: "iaaom3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aomni1_cop", field: "aomni1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aomni2_cop", field: "aomni2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aomni3_cop", field: "aomni3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "ima_n1", field: "ima_n1",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "ima_n2", field: "ima_n2",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "ima_n3", field: "ima_n3",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "imn_n1", field: "imn_n1",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "imn_n2", field: "imn_n2",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "imn_n3", field: "imn_n3",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aim_n1", field: "aim_n1",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aim_n2", field: "aim_n2",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aim_n3", field: "aim_n3",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "naim_n1", field: "naim_n1",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "naim_n2", field: "naim_n2",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "naim_n3", field: "naim_n3",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "fraccion_aim_n1_inversion", field: "fraccion_aim_n1_inversion",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "fraccion_aim_n1_aom", field: "fraccion_aim_n1_aom",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "bra1_cop", field: "bra1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "bra2_cop", field: "bra2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "bra3_cop", field: "bra3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "brae1_cop", field: "brae1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "brae2_cop", field: "brae2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "brae3_cop", field: "brae3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "braen1_cop", field: "braen1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "braen2_cop", field: "braen2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "braen3_cop", field: "braen3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "rc1_cop", field: "rc1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "rc2_cop", field: "rc2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "rc3_cop", field: "rc3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
// Continuación del arreglo
{ name: "cdi_aj_1_cop2007_kwh", field: "cdi_aj_1_cop2007_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cd_aj_2_cop2007_kwh", field: "cd_aj_2_cop2007_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cd_aj_3_cop2007_kwh", field: "cd_aj_3_cop2007_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "cdm_aj_1_cop2007_kwh", field: "cdm_aj_1_cop2007_kwh",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iapa1", field: "iapa1",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iapa2", field: "iapa2",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iapa3", field: "iapa3",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iapa1_tant", field: "iapa1_tant",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iapa2_tant", field: "iapa2_tant",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "iapa3_tant", field: "iapa3_tant",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "oi1_cop", field: "oi1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "oj2_cop", field: "oj2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "oj3_cop", field: "oj3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "irespaldo1_cop", field: "irespaldo1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "irespaldo2_cop", field: "irespaldo2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "irespaldo3_cop", field: "irespaldo3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "imunts1_cop", field: "imunts1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "imunts2_cop", field: "imunts2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "imunts3_cop", field: "imunts3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "ireactiva1_cop", field: "ireactiva1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "ireactiva2_cop", field: "ireactiva2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "ireactiva3_cop", field: "ireactiva3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aombase1", field: "aombase1",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aombase2", field: "aombase2",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "aombase3", field: "aombase3",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "brae1_tant_cop", field: "brae1_tant_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "brae2_tant_cop", field: "brae2_tant_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "brae3_tant_cop", field: "brae3_tant_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "deltabraenj_1_cop", field: "deltabraenj_1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "deltabraenj_2_cop", field: "deltabraenj_2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "deltabraenj_3_cop", field: "deltabraenj_3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "deltaingj_1_cop", field: "deltaingj_1_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "deltaingj_2_cop", field: "deltaingj_2_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},
{ name: "deltaingj_3_cop", field: "deltaingj_3_cop",  sortable: true,
    required: true,
    location: "center",
    showInForm: true,
    showInTable: true,
    clase: "input",
    type: "number",
    validations: "",
    description: ""},


];


export const headersData_xm_cprog = [
    {
      name: "Id",
      field: "id",
      sortable: true,
      required: false,
      location: "center",
      showInForm: false,
      showInTable: true,
      clase: "input",
      type: "number",
    },
    {
      name: "Eliminar",
      field: "Eliminar",
      sortable: false,
      required: false,
      location: "center",
      showInForm: false,
      showInTable: true,
      type: "button",
    },
    {
      name: "Creador",
      field: "creador",
      sortable: true,
      required: true,
      location: "center",
      showInForm: false,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "empresa id",
      field: "empresa_id",
      sortable: true,
      required: true,
      location: "center",
      showInForm: false,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "anho",
      field: "anho",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    {
      name: "mes",
      field: "mes",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: false,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },


    {
      name: "Agente",
      field: "agente",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "text",
      validations: "",
      description: "",
    },
    {
      name: "Cargo_Cprog_Cop_Kwh",
      field: "cargo_cprog_cop_kwh",
      sortable: true,
      required: true,
      location: "center",
      showInForm: true,
      showInTable: true,
      clase: "input",
      type: "number",
      validations: "",
      description: "",
    },
    
  ];
  
