const { DataTypes } = require("sequelize");
const db = require("../config/db.js");
const Data_Formato_9_SSPDSchema = db.define("Data_Formato_9_SSPD", {
  // Model attributes are defined here
  creador: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  empresa_id: { type: DataTypes.STRING, allowNull: false, trim: true },
  anho: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  mes: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  idmercado: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  ecc: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  vecc: { type: DataTypes.STRING, allowNull: false, trim: true },
 
  aecc: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  avecc: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  amc: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  cb_mr: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  vcb_mr: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  acb_mr: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  avcbmr: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  cb_mnr: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  vcb_mnr: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  agpe: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  gd: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  gtr: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  cug: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  clp: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  aclp: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  w: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  psa: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  egp: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  adm: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  vrm1: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  i: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  aj: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  alfa: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  dcr_agpe: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  admre: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  aprre_g: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  adr_iprstn: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  apr_iprstn: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  arest: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  cfj: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  rct: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  rcae: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  ifssri: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  ifoes: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  balancesubsidios: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  ano: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  trim: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  mgtrim: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  sub1: { type: DataTypes.STRING, allowNull: false, trim: true },
  sub2: { type: DataTypes.STRING, allowNull: false, trim: true },
  n: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  m: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  r1: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  r2: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  facturacion: { type: DataTypes.STRING, allowNull: false, trim: true },
  actividad: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  porc_creg_cx: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  porc_sspd_cx: { type: DataTypes.FLOAT, allowNull: false, trim: true },
  costo_creg_valor: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  costo_sspd_valor: { type: DataTypes.INTEGER, allowNull: false, trim: true },
  pui: { type: DataTypes.INTEGER, allowNull: false, trim: true },
});
module.exports = Data_Formato_9_SSPDSchema;
